services:
  - type: web
    name: mi-app-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      gunicorn GranGusano.wsgi:application
