# Generated by Django 4.2.23 on 2025-06-19 16:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
