knowledge_base = {
    "hola": "¡Hola! ¿En qué puedo ayudarte hoy?",
    "qué es el compostaje": "Es el proceso biológico de descomposición de materia orgánica, como restos de comida, hojas y papel, para producir abono natural.",
    "para qué sirve el compost": "El compost mejora la estructura del suelo, aporta nutrientes y ayuda a retener humedad, ideal para huertos y jardines.",
    "qué es la lombricultura": "Es la crianza y manejo de lombrices rojas californianas para la producción de humus y abono orgánico.",
    "qué comen las lombrices": "Comen restos vegetales, cáscaras de frutas, papel húmedo, posos de café y cartón sin tinta.",
    "qué no pueden comer las lombrices": "No deben comer cítricos, carne, pescado, lácteos, ajo, cebolla, aceites ni alimentos procesados.",
    "cuánto viven las lombrices": "Una lombriz roja californiana puede vivir entre 3 y 5 años en condiciones adecuadas.",
    "cómo se reproducen las lombrices": "Son hermafroditas y se reproducen al unirse dos lombrices para intercambiar esperma. Luego cada una pone cápsulas con embriones.",
    "cada cuánto se reproducen las lombrices": "Pueden poner una cápsula cada 7 a 10 días, y cada cápsula contiene de 2 a 5 lombrices.",
    "por qué usar lombrices californianas": "Son muy voraces, se reproducen rápido y producen un humus de alta calidad.",
    "qué es el humus de lombriz": "Es el resultado del proceso digestivo de las lombrices, un abono orgánico muy nutritivo.",
    "cuánto abono produce una lombriz": "Aproximadamente su propio peso por día en humus de lombriz.",
    "qué beneficios tiene el humus de lombriz": "Mejora la fertilidad del suelo, estimula el crecimiento de plantas y combate plagas.",
    "cuántas lombrices necesito para empezar": "Se recomienda comenzar con al menos 500 gramos a 1 kg de lombrices para compostaje doméstico.",
    "cómo cuidar las lombrices": "Mantén la humedad constante, buena ventilación, y aliméntalas regularmente sin excederte.",
    "cómo hacer una vermicompostera casera": "Puedes usar cajas plásticas con orificios para ventilación y drenaje, y taparlas del sol directo.",
    "dónde colocar la vermicompostera": "En un lugar fresco, oscuro y seco, lejos del sol directo y de la lluvia.",
    "qué temperatura es ideal para lombrices": "Entre 15°C y 25°C es ideal. Evita temperaturas extremas.",
    "qué hacer si las lombrices intentan escapar": "Revisa el pH, la humedad y los alimentos. Puede haber condiciones desfavorables.",
    "qué hacer si hay hormigas en la compostera": "Indica que está muy seca. Aumenta la humedad y revisa los restos de comida.",
    "qué hacer si hay moscas": "Indica exceso de humedad o restos de frutas mal cubiertos. Agrega más material seco.",
    "qué es el té de lombriz": "Es un líquido nutritivo que se obtiene al filtrar el humus en agua, y sirve como fertilizante foliar o de riego.",
    "cómo usar el té de lombriz": "Diluido en una proporción 1:10 en agua, se puede aplicar directamente a las hojas o al suelo.",
    "qué es el lixiviado": "Es el líquido que drena de la vermicompostera. Puede ser útil si no huele mal, pero debe diluirse antes de usar.",
    "cuándo recolectar el humus": "Cuando el material esté oscuro, sin olor y homogéneo, generalmente cada 2-3 meses.",
    "cómo separar las lombrices del humus": "Puedes mover el humus a un lado y colocar comida en el otro para que migren, o usar luz para que bajen.",
    "puedo usar lombrices silvestres": "No es recomendable, las rojas californianas son las más eficientes para compostaje.",
    "puedo compostar en departamento": "Sí, con una vermicompostera bien cuidada no genera olores ni molestias.",
    "qué hacer si el compost está muy seco": "Agrega restos húmedos (material verde) o rocía con agua sin pasarte.",
    "qué hacer si el compost huele mal": "Suele deberse al exceso de humedad o inclusión de materiales inadecuados como carnes o aceites.",
    "qué es la ecología del suelo": "Es el estudio de los organismos, minerales, aire y agua que interactúan en el suelo, afectando su fertilidad y salud.",
    "qué es la agricultura regenerativa": "Es una forma de cultivo que mejora la salud del suelo, aumenta la biodiversidad y captura carbono en el suelo.",
    "las lombrices mejoran el suelo": "Sí, airean el suelo, procesan materia orgánica y mejoran la disponibilidad de nutrientes.",
    "qué tipo de suelos prefieren las lombrices": "Suelos húmedos, con buena materia orgánica, pH neutro y temperatura moderada.",
    "puedo usar compost en plantas de interior": "Sí, en pequeñas cantidades mezclado con tierra común.",
    "puedo usar el compost en árboles frutales": "Sí, es ideal para árboles, mejora la calidad del fruto y fortalece las raíces.",
    "puedo compostar servilletas usadas": "Sí, si no tienen tinta o grasa. Son buen material marrón.",
    "puedo compostar cáscaras de huevo": "Sí, trituradas finamente ayudan a equilibrar el pH del compost.",
    "qué es material marrón": "Es el material seco como hojas, ramas, papel y cartón, rico en carbono.",
    "qué es material verde": "Restos de comida, césped recién cortado, y cáscaras de fruta, ricos en nitrógeno.",
    "qué es la proporción carbono-nitrógeno": "Una mezcla equilibrada es 3 partes de material marrón por 1 de verde.",
    "qué materiales debo evitar en el compost": "Carne, huesos, grasas, productos lácteos, excremento de mascotas y materiales con químicos.",
    "qué es el compost comunitario": "Es una iniciativa donde varios hogares comparten un punto de compostaje común.",
    "qué es la economía circular": "Es un modelo que busca reducir, reutilizar y reciclar para minimizar residuos y proteger el ambiente.",
    "cómo puedo reducir mi huella ecológica": "Recicla, reduce plásticos, usa transporte público, ahorra agua y energía.",
    "puedo compostar con niños": "Sí, es educativo y divertido. Enséñales qué materiales usar y cómo cuidarlo.",
    "cómo hacer compost en espacios pequeños": "Usa una vermicompostera vertical o baldes apilables con ventilación.",
    "qué hacer con el exceso de humus": "Puedes almacenarlo seco en bolsas, regalarlo, venderlo o usarlo en más macetas.",
    "el humus sirve para germinar semillas": "Sí, pero es mejor mezclarlo con tierra para evitar excesos de nutrientes.",
    "el humus ayuda contra enfermedades": "Sí, fortalece las plantas y puede reducir enfermedades fúngicas del suelo.",
    "qué pasa si llueve sobre la compostera": "Puede volverse demasiado húmeda y anaeróbica. Protégela con tapa o techo.",
    "cuántos niveles tiene una vermicompostera": "Generalmente tres: uno inferior para lixiviado, uno medio activo y uno superior para residuos nuevos.",
    "puedo vender el humus de lombriz": "Sí, es muy valorado en agricultura orgánica y jardinería urbana.",
    "qué otros animales ayudan al compost": "Escarabajos, colémbolos, ácaros y bacterias son esenciales en la descomposición.",
    "por qué es importante compostar": "Reduce los residuos, mejora los suelos, disminuye gases de efecto invernadero y cierra el ciclo natural de la materia.",
    "adiós": "¡Hasta luego! Recuerda cuidar el planeta.",
}

# Este diccionario contiene preguntas frecuentes y sus respuestas relacionadas con el compostaje y la lombricultura.