# Generated by Django 4.2.21 on 2025-06-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videollamadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videollamada',
            name='enlace',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
